apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate
  labels:
    app: rate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate
  template:
    metadata:
      labels:
        app: rate
    spec:
      containers:
      - name: rate
        image: microservi/social-hotel:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        command: ["/bin/sh", "-c"]
        args: ["/bin/rate 2>&1 | tee /root/deathstar_rate.output"]
        env:
        - name: SERVICE_NAME
          value: "rate"
        - name: REDIS_ADDR
          value: "rate-redis:6379"
        - name: GRPC_PORT
          value: "50051"
        - name: USER_SERVICE_ADDR
          value: "user-service:50051"
        - name: SEARCH_SERVICE_ADDR
          value: "search-service:50051"
        - name: RESERVATION_SERVICE_ADDR
          value: "reservation-service:50051"
        - name: RATE_SERVICE_ADDR
          value: "rate-service:50051"
        - name: PROFILE_SERVICE_ADDR
          value: "profile-service:50051"
        - name: MSGRAPH_YAML
          value: "/app/config/msgraph.yaml"
        volumeMounts:
          - name: config-volume
            mountPath: /app/config/msgraph.yaml
            subPath: msgraph.yaml
      volumes:
        - name: config-volume
          configMap:
            name: msgraph-config

