apiVersion: v1
kind: Service
metadata:
  name: usertimeline-redis
  labels:
    app: usertimeline-redis
spec:
  selector:
    app: usertimeline-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
