apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
  - name: http  # Name for the first port
    protocol: TCP
    port: 50051
    targetPort: 50051
    # Placeholder for additional port if needed
  type: LoadBalancer
  